### ISSUE TITLE
Easy widget test approach

### ISSUE THREAD

**Issue by rubensdemelo** [rodydavis/pocketbase_ui#1]
Hi Rod, I have a question about the easiest way to test widgets (ie MyHomePage):

```dart
          ValueListenableBuilder(
            valueListenable: App.of(context).themeMode,
```

`App` and `AppState` should be mocked and injected into the widget tree to test all possible states. 

Just building the widget, without testing anything related to the state, would be useful to mock only `App`?

Thanks

**Comment by rodydavis** [comment]
Yes totally, this was an example that I was building out for some apps exploring PocketBase. I wanted to stop repeating all the auth logic in my apps.

Haven't updated the example recently!

This is a great callout!
